### ISSUE TITLE
글자 얼굴 가림

### ISSUE THREAD

**Issue by ujuc** [sigmadream/Wedding-Template#3]
![screenshot_2017-10-17_13-12-07](https://user-images.githubusercontent.com/624975/31646441-d07bbf7a-b33c-11e7-82a3-c04cd88a3ceb.png)

모바일에서도 동일한 현상 발생.

다른 곳으로 옮기거나... 다른 방법 고안이 필요.

**Comment by sigmadream** [comment]
수정했음! 감사감사!
